import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/public/css/global.css";
import React, { useEffect } from 'react';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  useEffect(() => {
      (function() {
          window.$crisp = [];
          window.CRISP_WEBSITE_ID = process.env.CRISP_WEBSITE_ID;
          const d = document;
          const s = d.createElement('script');
          s.src = 'https://client.crisp.chat/l.js';
          s.async = true;
          d.head.appendChild(s);
      })();
  }, []);

  return (
      <div>
          {children}
      </div>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
